# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Linek Plumbing Company
email: contact@linekplumbing.com
phone: 314-962-0956
address: 24 Kirkham Industrial Ct. Webster Groves, MO 63119
description: > # this means to ignore newlines until "baseurl:"
  Linek Plumbing provides quality plumbing services for both commercial and residential projects across the St. Louis area. Since 1916.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://linekplbg.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

gems:
  - octopress-autoprefixer
  - jekyll-seo-tag

# Turn on for production
# sass:
#   style: compressed
